spring:
  application:
    name: eureka-provider
 
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
 
#logging:
#  level:
#    com.netflix: DEBUG