server:
  port: 9090
 
spring:
  application:
    name: eureka-consumer
 
eureka:
  client:
    registry-fetch-interval-seconds: 5  
    serviceUrl:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
logging:
  level:
    com.netflix: DEBUG      